#cloud-config
system_info:
  default_user:
    name: sysadmin
    gecos: sysadmin
    uid: "1010"

ssh_pwauth: true

chpasswd:
  expire: false

chpasswd:
  list:
    - sysadmin:sysadmin

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - 169.254.169.123

timezone: ROK
#timezone: Asia/Seoul

runcmd:
  - [ sed, -i, 's/#Port 22/Port 10022/g', /etc/ssh/sshd_config ]
  - [ systemctl, restart, sshd ]
  # - [ sudo, apt-get, autoremove, -y, needrestart]
  # - [ sudo, apt-get, update ]
  # - [ N, |, sudo, apt-get, upgrade, -y ]
  # - [ sudo, apt-get, install, -y, awscli ]
  # - [ sudo, apt-get, install, -y, nvme-cli ]
  # - [ sudo, apt-get, install, -y, net-tools ]  
  - [ sed, -i, 's/name: ubuntu/name: sysadmin/g', /etc/cloud/cloud.cfg ]
  - [ sed, -i, 's/lock_passwd: True/lock_passwd: False/g', /etc/cloud/cloud.cfg ]
  - [ sed, -i, 's/gecos: Ubuntu/gecos: sysadmin/g', /etc/cloud/cloud.cfg ]
  - [ sed, -i, 's/ssh_pwauth:   false/ssh_pwauth:   true/g', /etc/cloud/cloud.cfg ]

hostname: TEST
manage_etc_hosts: true

output:
    init:
        output: "> /var/log/cloud-init.out"
        error: "> /var/log/cloud-init.err"
    config: "tee -a /var/log/cloud-config.log"
    final:
        - ">> /var/log/cloud-final.out"
        - "/var/log/cloud-final.err"